// packages
import { defineConfig } from 'vite';

export default defineConfig({
	server: {
		open: true,
	},
	build: {
		// this removes the d.ts file generated by tsc so we do this ourselves
		emptyOutDir: false,
		lib: {
			entry: 'src/custom-element.ts',
			name: 'CustomElement',
			fileName: 'custom-element',
		},
	},
	plugins: [
		{
			name: 'vite-plugin-inline-favicon',
			apply: 'serve',
			configureServer(server) {
				const faviconString = `<svg xmlns='http://www.w3.org/2000/svg' width='48' height='48' viewBox='0 0 16 16'><text x='0' y='14'>🚧</text></svg>`;

				server.middlewares.use((request, response, next) => {
					if (request.url === '/favicon.ico') {
						response.setHeader('Content-Type', 'image/svg+xml');
						response.end(faviconString);
					} else {
						next();
					}
				});
			},
		},
	],
});
